version: "3.9"

services:
  tappy-frontend-app:
    container_name: tappy-frontend-app
    image: tappy-frontend-app:latest
    platform: "linux/amd64"
    build:
      context: .
      args:
        API_BASE_URL: ${API_BASE_URL}
        NEXT_PUBLIC_NODE_ENV: ${NEXT_PUBLIC_NODE_ENV}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - 3000:3000
